server:
  port: 9000

application:
  name: fileServer-01
eureka:
  server:
      #测试时关闭自我保护机制，保证不可用服务及时踢出
      enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/